In [20]:
import os
import pandas as pd
from IPython.display import display

pd.options.display.max_columns = None

In [21]:
data_path = os.getcwd() + "\Data\Raw_Data\cleaned_merged_seasons.csv"

df = pd.read_csv(data_path).iloc[:, 1:]
df.head()

C:\Users\GV147BE\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,season_x,name,position,team_x,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,opp_team_name,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,2016-17,Aaron Cresswell,DEF,NaN,0,0,0,0,0.0,454,10,0,0,0.0,0.0,2016-08-15T19:00:00Z,0,4,Chelsea,0,0,0,0,1,0,14023,1.0,2.0,0.0,0,0,0,0,55,False,0,1
1,2016-17,Aaron Lennon,MID,NaN,0,0,6,0,0.3,142,3,0,0,0.9,8.2,2016-08-13T14:00:00Z,15,17,Spurs,0,0,0,0,1,0,13918,1.0,1.0,0.0,1,0,0,0,60,True,0,1
2,2016-17,Aaron Ramsey,MID,NaN,0,0,5,0,4.9,16,8,3,0,3.0,2.2,2016-08-14T15:00:00Z,60,9,Liverpool,0,0,0,0,1,0,163170,4.0,3.0,23.0,2,0,0,0,80,True,0,1
3,2016-17,Abdoulaye Doucouré,MID,NaN,0,0,0,0,0.0,482,7,0,0,0.0,0.0,2016-08-13T14:00:00Z,0,13,Southampton,0,0,0,0,1,0,1051,1.0,1.0,0.0,0,0,0,0,50,False,0,1
4,2016-17,Adam Forshaw,MID,NaN,0,0,3,0,1.3,286,6,1,0,0.3,2.0,2016-08-13T14:00:00Z,69,14,Stoke,0,0,0,0,1,0,2723,1.0,1.0,0.0,1,0,0,0,45,True,1,1

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81775 entries, 0 to 81774
Data columns (total 37 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   season_x           81775 non-null  object
 1   name               81775 non-null  object
 2   position           81775 non-null  object
 3   team_x             32814 non-null  object
 4   assists            81775 non-null  int64
 5   bonus              81775 non-null  int64
 6   bps                81775 non-null  int64
 7   clean_sheets       81775 non-null  int64
 8   creativity         81775 non-null  float64
 9   element            81775 non-null  int64
 10  fixture            81775 non-null  int64
 11  goals_conceded     81775 non-null  int64
 12  goals_scored       81775 non-null  int64
 13  ict_index          81775 non-null  float64
 14  influence          81775 non-null  float64
 15  kickoff_time       81775 non-null  object
 16  minutes            81775 non-null  int64
 17  opponent_team      81775 non-null  int64
 18  opp_team_name      81775 non-null  object
 19  own_goals          81775 non-null  int64
 20  penalties_missed   81775 non-null  int64
 21  penalties_saved    81775 non-null  int64
 22  red_cards          81775 non-null  int64
 23  round              81775 non-null  int64
 24  saves              81775 non-null  int64
 25  selected           81775 non-null  int64
 26  team_a_score       81726 non-null  float64
 27  team_h_score       81726 non-null  float64
 28  threat             81775 non-null  float64
 29  total_points       81775 non-null  int64
 30  transfers_balance  81775 non-null  int64
 31  transfers_in       81775 non-null  int64
 32  transfers_out      81775 non-null  int64
 33  value              81775 non-null  int64
 34  was_home           81775 non-null  bool
 35  yellow_cards       81775 non-null  int64
 36  GW                 81775 non-null  int64
dtypes: bool(1), float64(6), int64(24), object(6)
memory usage: 22.5+ MB

In [11]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
assists,81775.0,0.047545,0.231201,0.0,0.0,0.0,0.0,4.0
bonus,81775.0,0.128071,0.531468,0.0,0.0,0.0,0.0,3.0
bps,81775.0,7.149471,10.388660,-18.0,0.0,0.0,12.0,114.0
clean_sheets,81775.0,0.126371,0.332269,0.0,0.0,0.0,0.0,1.0
creativity,81775.0,5.595215,11.492217,0.0,0.0,0.0,4.8,170.9
element,81775.0,302.646359,175.353290,1.0,153.0,297.0,450.0,713.0
fixture,81775.0,183.959217,111.038821,1.0,87.0,178.0,281.0,380.0
goals_conceded,81775.0,0.563607,1.004544,0.0,0.0,0.0,1.0,9.0
goals_scored,81775.0,0.053586,0.252925,0.0,0.0,0.0,0.0,4.0
ict_index,81775.0,2.059912,3.262573,0.0,0.0,0.1,3.0,35.8
influence,81775.0,8.601230,13.765836,0.0,0.0,0.0,13.8,163.6
minutes,81775.0,37.935482,41.732801,0.0,0.0,7.0,90.0,90.0
opponent_team,81775.0,10.495457,5.767722,1.0,5.0,10.0,15.0,20.0
own_goals,81775.0,0.001773,0.042072,0.0,0.0,0.0,0.0,1.0
penalties_missed,81775.0,0.001162,0.034064,0.0,0.0,0.0,0.0,1.0
penalties_saved,81775.0,0.000893,0.030272,0.0,0.0,0.0,0.0,2.0
red_cards,81775.0,0.002213,0.046995,0.0,0.0,0.0,0.0,1.0
round,81775.0,19.442299,11.952795,1.0,9.0,19.0,29.0,47.0
saves,81775.0,0.121198,0.707183,0.0,0.0,0.0,0.0,14.0
selected,81775.0,198793.187038,439105.945382,0.0,7787.5,36842.0,174029.0,6310003.0
team_a_score,81726.0,1.252380,1.210803,0.0,0.0,1.0,2.0,9.0
team_h_score,81726.0,1.485855,1.304331,0.0,1.0,1.0,2.0,9.0
threat,81775.0,6.413195,14.781198,0.0,0.0,0.0,4.0,186.0
total_points,81775.0,1.609257,2.690047,-7.0,0.0,0.0,2.0,29.0
transfers_balance,81775.0,1023.941999,58252.537482,-1734284.0,-1976.5,-106.0,150.0,1983733.0
transfers_in,81775.0,13976.801382,49980.293729,0.0,75.0,662.0,6167.5,2104464.0
transfers_out,81775.0,12952.127570,42965.887885,0.0,229.0,1605.0,9058.5,1782662.0
value,81775.0,52.837615,13.158395,38.0,45.0,49.0,56.0,136.0
yellow_cards,81775.0,0.060336,0.238110,0.0,0.0,0.0,0.0,1.0
GW,81775.0,19.442299,11.952795,1.0,9.0,19.0,29.0,47.0

In [13]:
df.isna().sum()

season_x                 0
name                     0
position                 0
team_x               48961
assists                  0
bonus                    0
bps                      0
clean_sheets             0
creativity               0
element                  0
fixture                  0
goals_conceded           0
goals_scored             0
ict_index                0
influence                0
kickoff_time             0
minutes                  0
opponent_team            0
opp_team_name            0
own_goals                0
penalties_missed         0
penalties_saved          0
red_cards                0
round                    0
saves                    0
selected                 0
team_a_score            49
team_h_score            49
threat                   0
total_points             0
transfers_balance        0
transfers_in             0
transfers_out            0
value                    0
was_home                 0
yellow_cards             0
GW                       0
dtype: int64

Note that team_x has around 50% blank entries. We deal with this below standardising the players team. All players will have only one team and it will be set as the latest team stored for that player
<br><br>
To do this we need to sort the dataset by date (kickoff_time).

In [27]:
df['kickoff_time'][0][-9:-1] #slice out time

'19:00:00'

In [29]:
df['kickoff_time'][0][:-10] #slice out date

'2016-08-15'

In [41]:
df['match_date'] = pd.to_datetime(df['kickoff_time'].apply(lambda x: x[:-10]) + " " + df['kickoff_time'].apply(lambda x: x[-9:-1]))
df.drop('kickoff_time', inplace=True, axis=1)
df['match_date'].head()

0   2016-08-15 19:00:00
1   2016-08-13 14:00:00
2   2016-08-14 15:00:00
3   2016-08-13 14:00:00
4   2016-08-13 14:00:00
Name: match_date, dtype: datetime64[ns]

In [75]:
#sort values by match date
df.sort_values(by=['match_date'], ascending=False, inplace=True)

#create dataset of only name instance
player_team = df.drop_duplicates(subset=['name'])[['name', 'team_x']]
player_team.reset_index(inplace=True, drop=True)
len(player_team.index)

905

In [76]:
player_team['team_x'].isna().sum() #check for null team values

0

In [77]:
player_team.head()

                   name   team_x
0       Mason Greenwood  Man Utd
1  Rúnar Alex Rúnarsson  Arsenal
2           Amad Diallo  Man Utd
3     Takehiro Tomiyasu  Arsenal
4       Martin Ødegaard  Arsenal

Merge datasets with most recent player teams

In [88]:
df = pd.merge(df, player_team, how='left', on=['name']).rename({'team_x_y':'team'})
df.drop('team_x_x', axis=1, inplace=True)
df.head()

C:\Users\GV147BE\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Passing 'suffixes' which cause duplicate columns {'team_x_x'} in the result is deprecated and will raise a MergeError in a future version.
  """Entry point for launching an IPython kernel.

,season_x,name,position,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,minutes,opponent_team,opp_team_name,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,match_date,match_time,team_x_y,team_x_y,team_x_y
0,2021-22,Mason Greenwood,MID,0,0,0,0,0.0,289,134,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,14,0,531047,2.0,3.0,0.0,0,-47779,1903,49682,73,True,0,14,2021-12-02 20:15:00,2022-02-22 20:15:00,Man Utd,Man Utd,Man Utd
1,2021-22,Rúnar Alex Rúnarsson,GK,0,0,0,0,0.0,2,134,0,0,0.0,0.0,0,13,Man Utd,0,0,0,0,14,0,63375,2.0,3.0,0.0,0,-816,0,816,40,False,0,14,2021-12-02 20:15:00,2022-02-22 20:15:00,Arsenal,Arsenal,Arsenal
2,2021-22,Amad Diallo,MID,0,0,0,0,0.0,636,134,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,14,0,0,2.0,3.0,0.0,0,0,0,0,50,True,0,14,2021-12-02 20:15:00,2022-02-22 20:15:00,Man Utd,Man Utd,Man Utd
3,2021-22,Takehiro Tomiyasu,DEF,0,0,11,0,18.4,590,134,3,0,3.2,13.2,90,13,Man Utd,0,0,0,0,14,0,329334,2.0,3.0,0.0,1,34593,43164,8571,46,False,0,14,2021-12-02 20:15:00,2022-02-22 20:15:00,Arsenal,Arsenal,Arsenal
4,2021-22,Martin Ødegaard,MID,0,0,26,0,54.5,558,134,3,1,10.7,35.4,78,13,Man Utd,0,0,0,0,14,0,107258,2.0,3.0,17.0,7,-1693,3833,5526,54,False,0,14,2021-12-02 20:15:00,2022-02-22 20:15:00,Arsenal,Arsenal,Arsenal

In [86]:
len(df.index)

81775

In [ ]:
#Check for missing values again