In [559]:
import os
import pandas as pd
from IPython.display import display

pd.options.display.max_columns = None

In [560]:
data_path = os.getcwd() + "\Data\Raw_Data\cleaned_merged_seasons.csv"

df = pd.read_csv(data_path).iloc[:, 1:]
df.head()

C:\Users\GV147BE\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,season_x,name,position,team_x,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,kickoff_time,minutes,opponent_team,opp_team_name,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW
0,2016-17,Aaron Cresswell,DEF,NaN,0,0,0,0,0.0,454,10,0,0,0.0,0.0,2016-08-15T19:00:00Z,0,4,Chelsea,0,0,0,0,1,0,14023,1.0,2.0,0.0,0,0,0,0,55,False,0,1
1,2016-17,Aaron Lennon,MID,NaN,0,0,6,0,0.3,142,3,0,0,0.9,8.2,2016-08-13T14:00:00Z,15,17,Spurs,0,0,0,0,1,0,13918,1.0,1.0,0.0,1,0,0,0,60,True,0,1
2,2016-17,Aaron Ramsey,MID,NaN,0,0,5,0,4.9,16,8,3,0,3.0,2.2,2016-08-14T15:00:00Z,60,9,Liverpool,0,0,0,0,1,0,163170,4.0,3.0,23.0,2,0,0,0,80,True,0,1
3,2016-17,Abdoulaye Doucouré,MID,NaN,0,0,0,0,0.0,482,7,0,0,0.0,0.0,2016-08-13T14:00:00Z,0,13,Southampton,0,0,0,0,1,0,1051,1.0,1.0,0.0,0,0,0,0,50,False,0,1
4,2016-17,Adam Forshaw,MID,NaN,0,0,3,0,1.3,286,6,1,0,0.3,2.0,2016-08-13T14:00:00Z,69,14,Stoke,0,0,0,0,1,0,2723,1.0,1.0,0.0,1,0,0,0,45,True,1,1

In [561]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81775 entries, 0 to 81774
Data columns (total 37 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   season_x           81775 non-null  object
 1   name               81775 non-null  object
 2   position           81775 non-null  object
 3   team_x             32814 non-null  object
 4   assists            81775 non-null  int64
 5   bonus              81775 non-null  int64
 6   bps                81775 non-null  int64
 7   clean_sheets       81775 non-null  int64
 8   creativity         81775 non-null  float64
 9   element            81775 non-null  int64
 10  fixture            81775 non-null  int64
 11  goals_conceded     81775 non-null  int64
 12  goals_scored       81775 non-null  int64
 13  ict_index          81775 non-null  float64
 14  influence          81775 non-null  float64
 15  kickoff_time       81775 non-null  object
 16  minutes            81775 non-null  int64
 17  opponent_team      81775 non-null  int64
 18  opp_team_name      81775 non-null  object
 19  own_goals          81775 non-null  int64
 20  penalties_missed   81775 non-null  int64
 21  penalties_saved    81775 non-null  int64
 22  red_cards          81775 non-null  int64
 23  round              81775 non-null  int64
 24  saves              81775 non-null  int64
 25  selected           81775 non-null  int64
 26  team_a_score       81726 non-null  float64
 27  team_h_score       81726 non-null  float64
 28  threat             81775 non-null  float64
 29  total_points       81775 non-null  int64
 30  transfers_balance  81775 non-null  int64
 31  transfers_in       81775 non-null  int64
 32  transfers_out      81775 non-null  int64
 33  value              81775 non-null  int64
 34  was_home           81775 non-null  bool
 35  yellow_cards       81775 non-null  int64
 36  GW                 81775 non-null  int64
dtypes: bool(1), float64(6), int64(24), object(6)
memory usage: 22.5+ MB

In [562]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
assists,81775.0,0.047545,0.231201,0.0,0.0,0.0,0.0,4.0
bonus,81775.0,0.128071,0.531468,0.0,0.0,0.0,0.0,3.0
bps,81775.0,7.149471,10.388660,-18.0,0.0,0.0,12.0,114.0
clean_sheets,81775.0,0.126371,0.332269,0.0,0.0,0.0,0.0,1.0
creativity,81775.0,5.595215,11.492217,0.0,0.0,0.0,4.8,170.9
element,81775.0,302.646359,175.353290,1.0,153.0,297.0,450.0,713.0
fixture,81775.0,183.959217,111.038821,1.0,87.0,178.0,281.0,380.0
goals_conceded,81775.0,0.563607,1.004544,0.0,0.0,0.0,1.0,9.0
goals_scored,81775.0,0.053586,0.252925,0.0,0.0,0.0,0.0,4.0
ict_index,81775.0,2.059912,3.262573,0.0,0.0,0.1,3.0,35.8
influence,81775.0,8.601230,13.765836,0.0,0.0,0.0,13.8,163.6
minutes,81775.0,37.935482,41.732801,0.0,0.0,7.0,90.0,90.0
opponent_team,81775.0,10.495457,5.767722,1.0,5.0,10.0,15.0,20.0
own_goals,81775.0,0.001773,0.042072,0.0,0.0,0.0,0.0,1.0
penalties_missed,81775.0,0.001162,0.034064,0.0,0.0,0.0,0.0,1.0
penalties_saved,81775.0,0.000893,0.030272,0.0,0.0,0.0,0.0,2.0
red_cards,81775.0,0.002213,0.046995,0.0,0.0,0.0,0.0,1.0
round,81775.0,19.442299,11.952795,1.0,9.0,19.0,29.0,47.0
saves,81775.0,0.121198,0.707183,0.0,0.0,0.0,0.0,14.0
selected,81775.0,198793.187038,439105.945382,0.0,7787.5,36842.0,174029.0,6310003.0
team_a_score,81726.0,1.252380,1.210803,0.0,0.0,1.0,2.0,9.0
team_h_score,81726.0,1.485855,1.304331,0.0,1.0,1.0,2.0,9.0
threat,81775.0,6.413195,14.781198,0.0,0.0,0.0,4.0,186.0
total_points,81775.0,1.609257,2.690047,-7.0,0.0,0.0,2.0,29.0
transfers_balance,81775.0,1023.941999,58252.537482,-1734284.0,-1976.5,-106.0,150.0,1983733.0
transfers_in,81775.0,13976.801382,49980.293729,0.0,75.0,662.0,6167.5,2104464.0
transfers_out,81775.0,12952.127570,42965.887885,0.0,229.0,1605.0,9058.5,1782662.0
value,81775.0,52.837615,13.158395,38.0,45.0,49.0,56.0,136.0
yellow_cards,81775.0,0.060336,0.238110,0.0,0.0,0.0,0.0,1.0
GW,81775.0,19.442299,11.952795,1.0,9.0,19.0,29.0,47.0

In [563]:
df.isna().sum()

season_x                 0
name                     0
position                 0
team_x               48961
assists                  0
bonus                    0
bps                      0
clean_sheets             0
creativity               0
element                  0
fixture                  0
goals_conceded           0
goals_scored             0
ict_index                0
influence                0
kickoff_time             0
minutes                  0
opponent_team            0
opp_team_name            0
own_goals                0
penalties_missed         0
penalties_saved          0
red_cards                0
round                    0
saves                    0
selected                 0
team_a_score            49
team_h_score            49
threat                   0
total_points             0
transfers_balance        0
transfers_in             0
transfers_out            0
value                    0
was_home                 0
yellow_cards             0
GW                       0
dtype: int64

Note that team_x has around 50% blank entries. We deal with this below standardising the players team. All players will have only one team and it will be set as the latest team stored for that player
<br><br>
To do this we need to sort the dataset by date (kickoff_time).

In [564]:
df['kickoff_time'][0][-9:-1] #slice out time

'19:00:00'

In [565]:
df['kickoff_time'][0][:-10] #slice out date

'2016-08-15'

In [566]:
df['match_date'] = pd.to_datetime(df['kickoff_time'].apply(lambda x: x[:-10]) + " " + df['kickoff_time'].apply(lambda x: x[-9:-1]))
df.drop('kickoff_time', inplace=True, axis=1)
df['match_date'].head()

0   2016-08-15 19:00:00
1   2016-08-13 14:00:00
2   2016-08-14 15:00:00
3   2016-08-13 14:00:00
4   2016-08-13 14:00:00
Name: match_date, dtype: datetime64[ns]

In [567]:
#sort values by match date
df.sort_values(by=['match_date'], ascending=False, inplace=True)

#create dataset of only name instance
player_team = df.drop_duplicates(subset=['name'])[['name', 'team_x']]
player_team.reset_index(inplace=True, drop=True)
len(player_team.index)

905

In [568]:
player_team['team_x'].isna().sum() #check for null team values

0

In [569]:
player_team.head()

                  name   team_x
0         David de Gea  Man Utd
1     Mattéo Guendouzi  Arsenal
2          Amad Diallo  Man Utd
3           Tom Heaton  Man Utd
4  Alex Nicolao Telles  Man Utd

Merge datasets with most recent player teams

In [570]:
df = pd.merge(df, player_team, how='left', on=['name']).rename(columns={'team_x_y':'team'})
df.drop('team_x_x', axis=1, inplace=True)
df.head()

,season_x,name,position,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,minutes,opponent_team,opp_team_name,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,match_date,team
0,2021-22,David de Gea,GK,0,0,17,0,0.0,270,134,2,0,3.4,34.4,90,1,Arsenal,0,0,0,0,14,5,473518,2.0,3.0,0.0,2,11244,19470,8226,50,True,0,14,2021-12-02 20:15:00,Man Utd
1,2021-22,Mattéo Guendouzi,MID,0,0,0,0,0.0,25,134,0,0,0.0,0.0,0,13,Man Utd,0,0,0,0,14,0,102,2.0,3.0,0.0,0,0,0,0,45,False,0,14,2021-12-02 20:15:00,Arsenal
2,2021-22,Amad Diallo,MID,0,0,0,0,0.0,636,134,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,14,0,0,2.0,3.0,0.0,0,0,0,0,50,True,0,14,2021-12-02 20:15:00,Man Utd
3,2021-22,Tom Heaton,GK,0,0,0,0,0.0,509,134,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,14,0,42318,2.0,3.0,0.0,0,-199,222,421,40,True,0,14,2021-12-02 20:15:00,Man Utd
4,2021-22,Alex Nicolao Telles,DEF,0,0,12,0,26.3,279,134,2,0,4.4,13.8,90,1,Arsenal,0,0,0,0,14,0,9011,2.0,3.0,4.0,1,2288,2676,388,50,True,0,14,2021-12-02 20:15:00,Man Utd

In [571]:
len(df.index) #check all rows are retained after merge

81775

In [572]:
#Check for missing values again
df.isna().sum()

season_x              0
name                  0
position              0
assists               0
bonus                 0
bps                   0
clean_sheets          0
creativity            0
element               0
fixture               0
goals_conceded        0
goals_scored          0
ict_index             0
influence             0
minutes               0
opponent_team         0
opp_team_name         0
own_goals             0
penalties_missed      0
penalties_saved       0
red_cards             0
round                 0
saves                 0
selected              0
team_a_score         49
team_h_score         49
threat                0
total_points          0
transfers_balance     0
transfers_in          0
transfers_out         0
value                 0
was_home              0
yellow_cards          0
GW                    0
match_date            0
team                  0
dtype: int64

Analysis the missing team_a_score and team_h_score

In [573]:
df[(df['team_a_score'].isna()) | (df['team_h_score'].isna())]

,season_x,name,position,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,minutes,opponent_team,opp_team_name,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,match_date,team
37286,2019-20,Emiliano Martínez,GK,0,0,0,0,0.0,427,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,17898,NaN,NaN,0.0,0,-81,92,173,43,False,0,29,2020-03-11 19:30:00,Aston Villa
37287,2019-20,Ainsley Maitland-Niles,DEF,0,0,0,0,0.0,4,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,172253,NaN,NaN,0.0,0,-1542,1682,3224,45,False,0,29,2020-03-11 19:30:00,Arsenal
37288,2019-20,Granit Xhaka,MID,0,0,0,0,0.0,18,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,58048,NaN,NaN,0.0,0,7927,9111,1184,51,False,0,29,2020-03-11 19:30:00,Arsenal
37289,2019-20,Héctor Bellerín,DEF,0,0,0,0,0.0,2,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,105290,NaN,NaN,0.0,0,23174,28916,5742,54,False,0,29,2020-03-11 19:30:00,Arsenal
37290,2019-20,Sokratis Papastathopoulos,DEF,0,0,0,0,0.0,5,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,106342,NaN,NaN,0.0,0,5315,7141,1826,48,False,0,29,2020-03-11 19:30:00,Arsenal
37291,2019-20,Pierre-Emerick Aubameyang,MID,0,0,0,0,0.0,11,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,2137772,NaN,NaN,0.0,0,670947,681665,10718,111,False,0,29,2020-03-11 19:30:00,Arsenal
37292,2019-20,Aymeric Laporte,DEF,0,0,0,0,0.0,202,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,147969,NaN,NaN,0.0,0,-7683,151,7834,63,True,0,29,2020-03-11 19:30:00,Man City
37293,2019-20,Cédric Soares,DEF,0,0,0,0,0.0,486,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,14788,NaN,NaN,0.0,0,-607,14,621,48,False,0,29,2020-03-11 19:30:00,Arsenal
37294,2019-20,Fernando Luiz Rosa,DEF,0,0,0,0,0.0,221,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,50852,NaN,NaN,0.0,0,1732,2484,752,52,True,0,29,2020-03-11 19:30:00,Man City
37295,2019-20,Kyle Walker,DEF,0,0,0,0,0.0,203,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,852022,NaN,NaN,0.0,0,55164,63486,8322,57,True,0,29,2020-03-11 19:30:00,Man City
37296,2019-20,Gabriel Teodoro Martinelli Silva,MID,0,0,0,0,0.0,504,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,217086,NaN,NaN,0.0,0,-24199,8945,33144,45,False,0,29,2020-03-11 19:30:00,Arsenal
37297,2019-20,Lucas Torreira,MID,0,0,0,0,0.0,19,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,84611,NaN,NaN,0.0,0,-3152,315,3467,47,False,0,29,2020-03-11 19:30:00,Arsenal
37298,2019-20,Ilkay Gündogan,MID,0,0,0,0,0.0,222,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,99918,NaN,NaN,0.0,0,9666,11761,2095,52,True,0,29,2020-03-11 19:30:00,Man City
37299,2019-20,Kevin De Bruyne,MID,0,0,0,0,0.0,215,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,3529427,NaN,NaN,0.0,0,-142889,121867,264756,107,True,0,29,2020-03-11 19:30:00,Man City
37300,2019-20,Daniel Ceballos Fernández,MID,0,0,0,0,0.0,469,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,229156,NaN,NaN,0.0,0,4911,6292,1381,52,False,0,29,2020-03-11 19:30:00,Arsenal
37301,2019-20,Rodrigo Hernandez,MID,0,0,0,0,0.0,443,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,146618,NaN,NaN,0.0,0,53608,58552,4944,54,True,0,29,2020-03-11 19:30:00,Man City
37302,2019-20,John Stones,DEF,0,0,0,0,0.0,207,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,73701,NaN,NaN,0.0,0,944,1510,566,53,True,0,29,2020-03-11 19:30:00,Man City
37303,2019-20,David Luiz Moreira Marinho,DEF,0,0,0,0,0.0,106,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,407755,NaN,NaN,0.0,0,31147,36340,5193,57,False,0,29,2020-03-11 19:30:00,Arsenal
37304,2019-20,Raheem Sterling,MID,0,0,0,0,0.0,214,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,1174941,NaN,NaN,0.0,0,54673,65423,10750,117,True,0,29,2020-03-11 19:30:00,Man City
37305,2019-20,Matteo Guendouzi,MID,0,0,0,0,0.0,21,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,420902,NaN,NaN,0.0,0,3458,15948,12490,43,False,0,29,2020-03-11 19:30:00,Arsenal
37306,2019-20,Bernardo Mota Veiga de Carvalho e Silva,MID,0,0,0,0,0.0,218,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,660240,NaN,NaN,0.0,0,45877,54552,8675,78,True,0,29,2020-03-11 19:30:00,Man City
37307,2019-20,Oleksandr Zinchenko,DEF,0,0,0,0,0.0,206,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,174780,NaN,NaN,0.0,0,286,1133,847,52,True,0,29,2020-03-11 19:30:00,Man City
37308,2019-20,Shkodran Mustafi,DEF,0,0,0,0,0.0,1,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,27137,NaN,NaN,0.0,0,-308,750,1058,51,False,0,29,2020-03-11 19:30:00,Arsenal
37309,2019-20,João Pedro Cavaco Cancelo,DEF,0,0,0,0,0.0,518,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,57546,NaN,NaN,0.0,0,-304,277,581,52,True,0,29,2020-03-11 19:30:00,Man City
37310,2019-20,Pablo Marí,DEF,0,0,0,0,0.0,617,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,2974,NaN,NaN,0.0,0,505,882,377,48,False,0,29,2020-03-11 19:30:00,Arsenal
37311,2019-20,Rob Holding,DEF,0,0,0,0,0.0,10,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,7836,NaN,NaN,0.0,0,-78,98,176,45,False,0,29,2020-03-11 19:30:00,Arsenal
37312,2019-20,Bernd Leno,GK,0,0,0,0,0.0,14,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,417485,NaN,NaN,0.0,0,28643,35845,7202,50,False,0,29,2020-03-11 19:30:00,Arsenal
37313,2019-20,Reiss Nelson,MID,0,0,0,0,0.0,489,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,7794,NaN,NaN,0.0,0,275,394,119,53,False,0,29,2020-03-11 19:30:00,Arsenal
37314,2019-20,Eric Garcia,DEF,0,0,0,0,0.0,544,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,3605,NaN,NaN,0.0,0,-74,74,148,45,True,0,29,2020-03-11 19:30:00,Man City
37315,2019-20,Ederson Santana de Moraes,GK,0,0,0,0,0.0,212,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,877151,NaN,NaN,0.0,0,34641,41977,7336,60,True,0,29,2020-03-11 19:30:00,Man City
37316,2019-20,Sead Kolasinac,DEF,0,0,0,0,0.0,3,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,35418,NaN,NaN,0.0,0,-530,12,542,52,False,0,29,2020-03-11 19:30:00,Arsenal
37317,2019-20,Benjamin Mendy,DEF,0,0,0,0,0.0,204,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,87467,NaN,NaN,0.0,0,22668,25749,3081,55,True,0,29,2020-03-11 19:30:00,Man City
37318,2019-20,Scott Carson,GK,0,0,0,0,0.0,562,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,5755,NaN,NaN,0.0,0,-114,114,228,40,True,0,29,2020-03-11 19:30:00,Man City
37319,2019-20,Calum Chambers,DEF,0,0,0,0,0.0,467,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,45603,NaN,NaN,0.0,0,-696,19,715,43,False,0,29,2020-03-11 19:30:00,Arsenal
37320,2019-20,Kieran Tierney,DEF,0,0,0,0,0.0,515,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,23850,NaN,NaN,0.0,0,-77,75,152,53,False,0,29,2020-03-11 19:30:00,Arsenal
37321,2019-20,Emile Smith Rowe,MID,0,0,0,0,0.0,576,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,3026,NaN,NaN,0.0,0,242,644,402,43,False,0,29,2020-03-11 19:30:00,Arsenal
37322,2019-20,Nicolas Pépé,MID,0,0,0,0,0.0,488,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,425610,NaN,NaN,0.0,0,133614,147166,13552,92,False,0,29,2020-03-11 19:30:00,Arsenal
37323,2019-20,Nicolás Otamendi,DEF,0,0,0,0,0.0,208,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,177006,NaN,NaN,0.0,0,21089,25210,4121,50,True,0,29,2020-03-11 19:30:00,Man City
37324,2019-20,Riyad Mahrez,MID,0,0,0,0,0.0,217,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,781785,NaN,NaN,0.0,0,211376,243769,32393,84,True,0,29,2020-03-11 19:30:00,Man City
37325,2019-20,Konstantinos Mavropanos,DEF,0,0,0,0,0.0,8,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,2829,NaN,NaN,0.0,0,-23,4,27,44,False,0,29,2020-03-11 19:30:00,Arsenal
37326,2019-20,Bukayo Saka,MID,0,0,0,0,0.0,541,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,397432,NaN,NaN,0.0,0,239781,248693,8912,46,False,0,29,2020-03-11 19:30:00,Arsenal
37327,2019-20,Claudio Bravo,GK,0,0,0,0,0.0,213,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,22598,NaN,NaN,0.0,0,-142,99,241,47,True,0,29,2020-03-11 19:30:00,Man City
37328,2019-20,Edward Nketiah,FWD,0,0,0,0,0.0,13,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,101003,NaN,NaN,0.0,0,34253,39328,5075,43,False,0,29,2020-03-11 19:30:00,Arsenal
37329,2019-20,Joseph Willock,MID,0,0,0,0,0.0,490,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,12990,NaN,NaN,0.0,0,79,288,209,47,False,0,29,2020-03-11 19:30:00,Newcastle
37330,2019-20,Mesut Özil,MID,0,0,0,0,0.0,15,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,115775,NaN,NaN,0.0,0,23726,28433,4707,72,False,0,29,2020-03-11 19:30:00,Arsenal
37331,2019-20,Alexandre Lacazette,FWD,0,0,0,0,0.0,12,275,0,0,0.0,0.0,0,11,Man City,0,0,0,0,29,0,159656,NaN,NaN,0.0,0,9564,19224,9660,93,False,0,29,2020-03-11 19:30:00,Arsenal
37332,2019-20,Sergio Agüero,FWD,0,0,0,0,0.0,210,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,1369119,NaN,NaN,0.0,0,23468,116583,93115,119,True,0,29,2020-03-11 19:30:00,Man City
37333,2019-20,Gabriel Fernando de Jesus,FWD,0,0,0,0,0.0,211,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,248940,NaN,NaN,0.0,0,58216,67141,8925,95,True,0,29,2020-03-11 19:30:00,Man City
37334,2019-20,Phil Foden,MID,0,0,0,0,0.0,220,275,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,29,0,27337,NaN,NaN,0.0,0,5144,5892,748,51,True,0,29,2020-03-11 19:30:00,Man City

Note the only missing values are for Arsenal vs Man City on the 11/03/20 at 7:30. This match does not exist. hence we can delete these rows.

In [574]:
df.dropna(axis=0, inplace=True)
len(df.index) #check only 49 rows have been removed

81726

<h1> Now we have no missing values in our dataset! </h1>

Now we are going to analyse the non-numeric columns

In [575]:
df.select_dtypes(['object']).columns

Index(['season_x', 'name', 'position', 'opp_team_name', 'team'], dtype='object')

The only column that may be useful to our is team and opposition team. So we will create dummy variables for team column. We will create a ranking system for opp_team_name.

In [576]:
df['opp_team_name'].value_counts()

Man City          4091
Everton           4086
Chelsea           4072
Crystal Palace    4065
Liverpool         4065
Southampton       4064
Arsenal           4063
West Ham          4063
Spurs             4060
Leicester         4053
Burnley           4044
Man Utd           4039
Brighton          3696
Newcastle         3665
Wolves            3148
Watford           2891
Bournemouth       2516
Aston Villa       2496
West Brom         2160
Sheffield Utd     2084
Fulham            1866
Leeds             1636
Norwich           1303
Huddersfield      1246
Stoke              958
Swansea            941
Cardiff            694
Brentford          425
Sunderland         416
Middlesbrough      414
Hull               406
Name: opp_team_name, dtype: int64

In [577]:
df['season_x'].value_counts()

2020-21    24365
2019-20    17068
2018-19    13273
2017-18    10568
2021-22     8449
2016-17     8003
Name: season_x, dtype: int64

In [578]:
data_path = os.getcwd() + "\Data\Raw_Data\EPL_Tables.csv"

prem_tables = pd.read_csv(data_path)
prem_tables.head()

        Team  Position   Season
0   Man City         1  2020-21
1    Man Utd         2  2020-21
2  Liverpool         3  2020-21
3    Chelsea         4  2020-21
4  Leicester         5  2020-21

In [579]:
prem_tables['Season'].value_counts()

2020-21    20
2019-20    20
2021-22    20
2018-19    20
2017-18    20
2016-17    20
Name: Season, dtype: int64

In [580]:
#Score teams based on which quarter of the table they are in
def quartile_scoring(x):
    
    if x <=5:
        return 1
    elif x <=10:
        return 2
    elif x<=15:
        return 3
    else:
        return 4

prem_tables['opp_team_rating'] = prem_tables['Position'].apply(lambda x: quartile_scoring(x))
#drop Position column
prem_tables.drop('Position', axis=1, inplace=True)
prem_tables.head()

        Team   Season  opp_team_rating
0   Man City  2020-21                1
1    Man Utd  2020-21                1
2  Liverpool  2020-21                1
3    Chelsea  2020-21                1
4  Leicester  2020-21                1

In [549]:
#match key column names
df.rename(columns={'season_x': 'Season'}, inplace=True)
prem_tables.rename(columns={'Team': 'opp_team_name'}, inplace=True)

df = pd.merge(df, prem_tables, how='left', on=['Season', 'opp_team_name']).drop(['opp_team_name', 'opp_team'])
df.head()

,Season,name,position,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,minutes,opponent_team,opp_team_name,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,match_date,team,opp_team_rating
0,2021-22,David de Gea,GK,0,0,17,0,0.0,270,134,2,0,3.4,34.4,90,1,Arsenal,0,0,0,0,14,5,473518,2.0,3.0,0.0,2,11244,19470,8226,50,True,0,14,2021-12-02 20:15:00,Man Utd,2
1,2021-22,Mattéo Guendouzi,MID,0,0,0,0,0.0,25,134,0,0,0.0,0.0,0,13,Man Utd,0,0,0,0,14,0,102,2.0,3.0,0.0,0,0,0,0,45,False,0,14,2021-12-02 20:15:00,Arsenal,1
2,2021-22,Amad Diallo,MID,0,0,0,0,0.0,636,134,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,14,0,0,2.0,3.0,0.0,0,0,0,0,50,True,0,14,2021-12-02 20:15:00,Man Utd,2
3,2021-22,Tom Heaton,GK,0,0,0,0,0.0,509,134,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,14,0,42318,2.0,3.0,0.0,0,-199,222,421,40,True,0,14,2021-12-02 20:15:00,Man Utd,2
4,2021-22,Alex Nicolao Telles,DEF,0,0,12,0,26.3,279,134,2,0,4.4,13.8,90,1,Arsenal,0,0,0,0,14,0,9011,2.0,3.0,4.0,1,2288,2676,388,50,True,0,14,2021-12-02 20:15:00,Man Utd,2

Now we have added in Rankings for the opponend team we will now, create dummy variables for the player's team.

In [584]:
dummies = pd.get_dummies(df['team'],drop_first=False)
#df = df.drop(['team'],axis=1) #do not drop team column as we will use this later on
df = pd.concat([df,dummies],axis=1)
df.head()

,season_x,name,position,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,minutes,opponent_team,opp_team_name,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,match_date,team,Arsenal,Aston Villa,Brentford,Brighton,Burnley,Chelsea,Crystal Palace,Everton,Fulham,Leeds,Leicester,Liverpool,Man City,Man Utd,Newcastle,Norwich,Sheffield Utd,Southampton,Spurs,Watford,West Brom,West Ham,Wolves
0,2021-22,David de Gea,GK,0,0,17,0,0.0,270,134,2,0,3.4,34.4,90,1,Arsenal,0,0,0,0,14,5,473518,2.0,3.0,0.0,2,11244,19470,8226,50,True,0,14,2021-12-02 20:15:00,Man Utd,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
1,2021-22,Mattéo Guendouzi,MID,0,0,0,0,0.0,25,134,0,0,0.0,0.0,0,13,Man Utd,0,0,0,0,14,0,102,2.0,3.0,0.0,0,0,0,0,45,False,0,14,2021-12-02 20:15:00,Arsenal,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2021-22,Amad Diallo,MID,0,0,0,0,0.0,636,134,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,14,0,0,2.0,3.0,0.0,0,0,0,0,50,True,0,14,2021-12-02 20:15:00,Man Utd,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
3,2021-22,Tom Heaton,GK,0,0,0,0,0.0,509,134,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,14,0,42318,2.0,3.0,0.0,0,-199,222,421,40,True,0,14,2021-12-02 20:15:00,Man Utd,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4,2021-22,Alex Nicolao Telles,DEF,0,0,12,0,26.3,279,134,2,0,4.4,13.8,90,1,Arsenal,0,0,0,0,14,0,9011,2.0,3.0,4.0,1,2288,2676,388,50,True,0,14,2021-12-02 20:15:00,Man Utd,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0

<h1>Now we have dealt with useful categorical values </h1>

Next we want to find values that are correlated with total_points. Before we do this we fill split the dataset into 4, GK, DEF, MID and FWD.

In [585]:
goalkeepers = df[df['position']=="GK"]
print(len(goalkeepers.index))
goalkeepers.head()

9167

,season_x,name,position,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,minutes,opponent_team,opp_team_name,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,match_date,team,Arsenal,Aston Villa,Brentford,Brighton,Burnley,Chelsea,Crystal Palace,Everton,Fulham,Leeds,Leicester,Liverpool,Man City,Man Utd,Newcastle,Norwich,Sheffield Utd,Southampton,Spurs,Watford,West Brom,West Ham,Wolves
0,2021-22,David de Gea,GK,0,0,17,0,0.0,270,134,2,0,3.4,34.4,90,1,Arsenal,0,0,0,0,14,5,473518,2.0,3.0,0.0,2,11244,19470,8226,50,True,0,14,2021-12-02 20:15:00,Man Utd,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
3,2021-22,Tom Heaton,GK,0,0,0,0,0.0,509,134,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,14,0,42318,2.0,3.0,0.0,0,-199,222,421,40,True,0,14,2021-12-02 20:15:00,Man Utd,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
5,2021-22,Dean Henderson,GK,0,0,0,0,0.0,280,134,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,14,0,36124,2.0,3.0,0.0,0,-333,71,404,47,True,0,14,2021-12-02 20:15:00,Man Utd,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
22,2021-22,Bernd Leno,GK,0,0,0,0,0.0,1,134,0,0,0.0,0.0,0,13,Man Utd,0,0,0,0,14,0,83324,2.0,3.0,0.0,0,-1431,321,1752,46,False,0,14,2021-12-02 20:15:00,Arsenal,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
24,2021-22,Aaron Ramsdale,GK,0,0,23,0,0.0,559,134,3,0,4.7,47.4,90,13,Man Utd,0,0,0,0,14,7,1125402,2.0,3.0,0.0,3,52163,74772,22609,49,False,0,14,2021-12-02 20:15:00,Arsenal,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [586]:
defenders = df[df['position']=="DEF"]
print(len(defenders.index))
defenders.head()

29342

,season_x,name,position,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,minutes,opponent_team,opp_team_name,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,match_date,team,Arsenal,Aston Villa,Brentford,Brighton,Burnley,Chelsea,Crystal Palace,Everton,Fulham,Leeds,Leicester,Liverpool,Man City,Man Utd,Newcastle,Norwich,Sheffield Utd,Southampton,Spurs,Watford,West Brom,West Ham,Wolves
4,2021-22,Alex Nicolao Telles,DEF,0,0,12,0,26.3,279,134,2,0,4.4,13.8,90,1,Arsenal,0,0,0,0,14,0,9011,2.0,3.0,4.0,1,2288,2676,388,50,True,0,14,2021-12-02 20:15:00,Man Utd,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
7,2021-22,Luke Shaw,DEF,0,0,0,0,0.0,275,134,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,14,0,1315061,2.0,3.0,0.0,0,-78275,742,79017,51,True,0,14,2021-12-02 20:15:00,Man Utd,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
8,2021-22,William Saliba,DEF,0,0,0,0,0.0,27,134,0,0,0.0,0.0,0,13,Man Utd,0,0,0,0,14,0,214,2.0,3.0,0.0,0,0,0,0,45,False,0,14,2021-12-02 20:15:00,Arsenal,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,2021-22,Kieran Tierney,DEF,0,0,0,0,0.0,16,134,0,0,0.0,0.0,0,13,Man Utd,0,0,0,0,14,0,323534,2.0,3.0,0.0,0,-34096,894,34990,47,False,0,14,2021-12-02 20:15:00,Arsenal,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
15,2021-22,Takehiro Tomiyasu,DEF,0,0,11,0,18.4,590,134,3,0,3.2,13.2,90,13,Man Utd,0,0,0,0,14,0,329334,2.0,3.0,0.0,1,34593,43164,8571,46,False,0,14,2021-12-02 20:15:00,Arsenal,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [587]:
midfielders = df[df['position']=="MID"]
print(len(midfielders.index))
midfielders.head()

31984

,season_x,name,position,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,minutes,opponent_team,opp_team_name,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,match_date,team,Arsenal,Aston Villa,Brentford,Brighton,Burnley,Chelsea,Crystal Palace,Everton,Fulham,Leeds,Leicester,Liverpool,Man City,Man Utd,Newcastle,Norwich,Sheffield Utd,Southampton,Spurs,Watford,West Brom,West Ham,Wolves
1,2021-22,Mattéo Guendouzi,MID,0,0,0,0,0.0,25,134,0,0,0.0,0.0,0,13,Man Utd,0,0,0,0,14,0,102,2.0,3.0,0.0,0,0,0,0,45,False,0,14,2021-12-02 20:15:00,Arsenal,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2021-22,Amad Diallo,MID,0,0,0,0,0.0,636,134,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,14,0,0,2.0,3.0,0.0,0,0,0,0,50,True,0,14,2021-12-02 20:15:00,Man Utd,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
6,2021-22,Granit Xhaka,MID,0,0,0,0,0.0,7,134,0,0,0.0,0.0,0,13,Man Utd,0,0,0,0,14,0,24703,2.0,3.0,0.0,0,-198,39,237,48,False,0,14,2021-12-02 20:15:00,Arsenal,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,2021-22,Gabriel Teodoro Martinelli Silva,MID,1,0,17,0,33.1,26,134,3,0,8.6,21.0,90,13,Man Utd,0,0,0,0,14,0,16436,2.0,3.0,32.0,5,2705,3033,328,52,False,0,14,2021-12-02 20:15:00,Arsenal,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,2021-22,Mason Greenwood,MID,0,0,0,0,0.0,289,134,0,0,0.0,0.0,0,1,Arsenal,0,0,0,0,14,0,531047,2.0,3.0,0.0,0,-47779,1903,49682,73,True,0,14,2021-12-02 20:15:00,Man Utd,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0

In [588]:
forwards = df[df['position']=="FWD"]
print(len(forwards.index))
forwards.head()

11233

,season_x,name,position,assists,bonus,bps,clean_sheets,creativity,element,fixture,goals_conceded,goals_scored,ict_index,influence,minutes,opponent_team,opp_team_name,own_goals,penalties_missed,penalties_saved,red_cards,round,saves,selected,team_a_score,team_h_score,threat,total_points,transfers_balance,transfers_in,transfers_out,value,was_home,yellow_cards,GW,match_date,team,Arsenal,Aston Villa,Brentford,Brighton,Burnley,Chelsea,Crystal Palace,Everton,Fulham,Leeds,Leicester,Liverpool,Man City,Man Utd,Newcastle,Norwich,Sheffield Utd,Southampton,Spurs,Watford,West Brom,West Ham,Wolves
11,2021-22,Alexandre Lacazette,FWD,0,0,3,0,0.0,6,134,0,0,0.0,0.2,11,13,Man Utd,0,0,0,0,14,0,96187,2.0,3.0,0.0,1,-5515,1163,6678,83,False,0,14,2021-12-02 20:15:00,Arsenal,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,2021-22,Anthony Martial,FWD,0,0,3,0,0.0,278,134,0,0,0.0,0.0,2,1,Arsenal,0,0,0,0,14,0,50595,2.0,3.0,0.0,1,-144,576,720,76,True,0,14,2021-12-02 20:15:00,Man Utd,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
14,2021-22,Cristiano Ronaldo dos Santos Aveiro,FWD,0,3,53,0,2.9,579,134,2,2,14.9,71.0,87,1,Arsenal,0,0,0,0,14,0,2348347,2.0,3.0,75.0,13,-176787,20085,196872,123,True,0,14,2021-12-02 20:15:00,Man Utd,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
16,2021-22,Edward Nketiah,FWD,0,0,6,0,0.5,20,134,0,0,0.4,3.2,11,13,Man Utd,0,0,0,0,14,0,11032,2.0,3.0,0.0,1,-25,512,537,54,False,0,14,2021-12-02 20:15:00,Arsenal,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
26,2021-22,Pierre-Emerick Aubameyang,FWD,0,0,3,0,2.1,4,134,3,0,8.5,12.6,78,13,Man Utd,0,0,0,0,14,0,298113,2.0,3.0,70.0,2,-92172,3897,96069,98,False,0,14,2021-12-02 20:15:00,Arsenal,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

Drop the values that have a correlation score betweem -.4 and .4.

In [590]:
goalkeepers.corr()['total_points'].sort_values()

team_a_score        -0.152967
element             -0.141542
team_h_score        -0.117086
Sheffield Utd       -0.078319
Fulham              -0.057845
Norwich             -0.034864
Aston Villa         -0.029612
red_cards           -0.024090
West Brom           -0.017656
Brentford           -0.016997
Newcastle           -0.015904
Chelsea             -0.015750
Leeds               -0.015471
own_goals           -0.014933
Burnley             -0.013264
Southampton         -0.009373
round               -0.008753
GW                  -0.008753
fixture             -0.008501
Wolves              -0.002943
opponent_team       -0.001884
Leicester            0.000402
Man Utd              0.009368
Brighton             0.014037
Man City             0.015958
Liverpool            0.016124
threat               0.016608
was_home             0.018247
Arsenal              0.020177
Crystal Palace       0.020782
West Ham             0.021787
Spurs                0.022483
Everton              0.034903
Watford              0.041634
goals_scored         0.042281
yellow_cards         0.059882
assists              0.106165
goals_conceded       0.112729
transfers_balance    0.114232
creativity           0.136877
transfers_out        0.172512
transfers_in         0.294885
penalties_saved      0.323698
selected             0.377299
value                0.428905
saves                0.654400
ict_index            0.695726
influence            0.697381
bonus                0.709436
minutes              0.718831
clean_sheets         0.829100
bps                  0.921300
total_points         1.000000
penalties_missed          NaN
Name: total_points, dtype: float64

In [593]:
goalkeepers = goalkeepers[['total_points', 'bps', 'clean_sheets', 'minutes', 'bonus', 'influence', 
                          'ict_index', 'saves', 'value', 'selected', 'penalties_saved']]
goalkeepers.head()

,total_points,bps,clean_sheets,minutes,bonus,influence,ict_index,saves,value,selected,penalties_saved
0,2,17,0,90,0,34.4,3.4,5,50,473518,0
3,0,0,0,0,0,0.0,0.0,0,40,42318,0
5,0,0,0,0,0,0.0,0.0,0,47,36124,0
22,0,0,0,0,0,0.0,0.0,0,46,83324,0
24,3,23,0,90,0,47.4,4.7,7,49,1125402,0

In [556]:
defenders.corr()['total_points'].sort_values()

team_a_score        -0.122063
team_h_score        -0.092656
element             -0.085930
red_cards           -0.065670
own_goals           -0.046308
goals_conceded      -0.040657
fixture             -0.001492
opponent_team        0.000522
GW                   0.000839
round                0.000839
was_home             0.050045
yellow_cards         0.055082
transfers_out        0.078072
opp_team_rating      0.113849
transfers_balance    0.127226
transfers_in         0.216044
selected             0.255503
value                0.260613
creativity           0.378659
assists              0.380740
threat               0.427404
goals_scored         0.461734
minutes              0.601556
ict_index            0.665905
influence            0.699575
bonus                0.699911
clean_sheets         0.794791
bps                  0.882453
total_points         1.000000
penalties_missed          NaN
penalties_saved           NaN
saves                     NaN
Name: total_points, dtype: float64

In [557]:
midfielders.corr()['total_points'].sort_values()

element             -0.110175
red_cards           -0.042406
own_goals           -0.015805
round               -0.015093
GW                  -0.015093
fixture             -0.014474
opponent_team        0.005590
penalties_missed     0.013206
was_home             0.035639
yellow_cards         0.042915
team_a_score         0.058844
opp_team_rating      0.066603
team_h_score         0.087684
transfers_balance    0.104153
transfers_out        0.138589
transfers_in         0.235991
goals_conceded       0.241521
selected             0.310231
value                0.348539
clean_sheets         0.416327
creativity           0.538348
assists              0.541486
minutes              0.617796
threat               0.632453
bonus                0.770456
goals_scored         0.791333
ict_index            0.820406
influence            0.917914
bps                  0.918834
total_points         1.000000
penalties_saved           NaN
saves                     NaN
Name: total_points, dtype: float64

In [558]:
forwards.corr()['total_points'].sort_values()

element             -0.085459
red_cards           -0.038233
fixture             -0.014856
round               -0.013170
GW                  -0.013170
opponent_team        0.008126
own_goals            0.012271
penalties_missed     0.013338
was_home             0.017344
opp_team_rating      0.079221
yellow_cards         0.084573
transfers_balance    0.114340
team_a_score         0.120999
team_h_score         0.125322
transfers_out        0.142983
transfers_in         0.263570
goals_conceded       0.310069
selected             0.323317
clean_sheets         0.334323
value                0.341274
assists              0.460252
creativity           0.539827
minutes              0.641322
threat               0.707212
bonus                0.835399
ict_index            0.864025
goals_scored         0.882820
influence            0.949357
bps                  0.958605
total_points         1.000000
penalties_saved           NaN
saves                     NaN
Name: total_points, dtype: float64